version: '3.7'
services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:8052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:8051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_TLS_ENABLED=true

    volumes:
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock

    ports:
    - 8051:8051
    networks:
    - test
  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer:2.5
    environment:
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_ADDRESS=peer1.org2.example.com:9051
    - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
    - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:9052
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:9051
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_TLS_ENABLED=true

    volumes:
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
    - ../organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
    - /var/run/docker.sock:/var/run/docker.sock


    ports:
    - 10051:9051
    networks:
    - test
